[package]
name = "kujira-rs-testing"
version = "1.1.0"
authors = ["Kujira Labs"]
edition = "2018"
description = "Interfaces and utilities for Kujira cosmwasm contracts"
license = "Apache-2.0"
homepage = "https://kujira.app"
repository = "https://github.com/Team-Kujira/kujira-rs"

[features]
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-std = { workspace = true }
cosmwasm-schema = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true, default-features = false, features = ["derive"] }
cw-multi-test = "0.16"
cw-storage-plus = "1.0"
anyhow = { workspace = true}
kujira = { version = "0.8", path = "../kujira" }
serde_json = {workspace = true}
base64 = "0.20.0"
hex = { workspace = true }
cw20 = { workspace = true }
